school/classroom/urls.py
from django.urls import path
from .views import (HomeView, ThankYouView,
                    ContactFormView, TeacherCreateView,
                    TeacherListView, TeacherDetailView,
                    TeacherUpdateView, TeacherDeleteView)

app_name = 'classroom'

# domain.com/classroom/
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('thank_you/', ThankYouView.as_view(), name='thank_you'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('create_teacher/', TeacherCreateView.as_view(), name='create_teacher'),
    path('list_teacher', TeacherListView.as_view(), name='list_teacher'),
    path('detail_teacher/<int:pk>/', TeacherDetailView.as_view(), name='detail_teacher'),
    path('update_teacher/<int:pk>/', TeacherUpdateView.as_view(), name='update_teacher'),
    path('delete_teacher/<int:pk>/', TeacherDeleteView.as_view(), name='delete_teacher'),
]

school/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/', include('classroom.urls')),
]

school/classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.first_name} {self.last_name} teaches {self.subject}'

school/classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(

    )
    message = forms.CharField(widget=forms.Textarea)

school/classroom/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView

from classroom.forms import ContactForm
from classroom.models import Teacher


# Create your views here.
class HomeView(TemplateView):
    template_name = 'classroom/home.html'


class ThankYouView(TemplateView):
    template_name = 'classroom/thank_you.html'


# Creating new Instance of Model
class TeacherCreateView(CreateView):
    model = Teacher
    # model_form.html (find template automatically)
    # .save()
    fields = '__all__'
    success_url = reverse_lazy('classroom:thank_you')


class TeacherListView(ListView):
    model = Teacher
    # model_list.html
    queryset = Teacher.objects.order_by('first_name')
    context_object_name = 'teachers'


# RETURN ONLY ONE MODEL ENTRY PK
class TeacherDetailView(DetailView):
    model = Teacher
    # model_detail.html
    # PK -> {{ teacher }}


class TeacherUpdateView(UpdateView):
    model = Teacher
    # SHARE model_form.html
    fields = '__all__'
    success_url = reverse_lazy('classroom:list_teacher')


# Form -> Confirm Delete Button
class TeacherDeleteView(DeleteView):
    model = Teacher
    # model_confirm_delete.html
    success_url = reverse_lazy('classroom:list_teacher')


class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'

    # success URL
    # TODO: 이 부분 더 정리하기!
    success_url = reverse_lazy('classroom:thank_you')

    # what to do with form?
    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

school/classroom/templates/classroom/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Form View Template (contact.html)</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

school/classroom/templates/classroom/home.html
<h1>Welcome to HOME</h1>
<ul>
    <li>
        <a href="{% url "classroom:thank_you" %}">THANK YOU PAGE LINK</a>
    </li>
    <li>
        <a href="{% url "classroom:contact" %}">CONTACT FORM PAGE LINK</a>
    </li>
    <li>
        <a href="{% url "classroom:create_teacher" %}">CREATE NEW TEACHER PAGE LINK</a>
    </li>
    <li>
        <a href="{% url "classroom:list_teacher" %}">LIST TEACHER PAGE LINK</a>
    </li>
</ul>

school/classroom/templates/classroom/teacher_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Are you sure you want to delete this teacher?</h1>
<h2>{{ teacher }}</h2>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Confirm Delete">
    </form>
</body>
</html>

school/classroom/templates/classroom/teacher_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Detail View for a Teacher</h1>
    {{ teacher }}
</body>
</html>

school/classroom/templates/classroom/teacher_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Teacher Form</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

school/classroom/templates/classroom/teacher_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>List of Teachers (ListView)</h1>
    <ul>
        {% for teacher in teachers %}
            <li><a href="/classroom/detail_teacher/{{ teacher.id }}">{{ teacher.first_name }} {{ teacher.last_name }}</a></li>
            <ul>
                <li><a href="/classroom/update_teacher/{{ teacher.id }}">Update Information</a></li>
                <li><a href="/classroom/delete_teacher/{{ teacher.id }}">DELETE</a></li>
            </ul>
        {% endfor %}
    </ul>
</body>
</html>

school/classroom/templates/classroom/thank_you.html
<h1>THANK YOU</h1>