car_site/car_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', include('cars.urls')),
]

car_site/cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
    path('list/', views.list, name='list'),
]

car_site/cars/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    brand = models.CharField(max_length=30)
    year = models.IntegerField()

    def __str__(self):
        return f'{self.pk}: {self.brand}, {self.year}'

car_site/cars/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models

# Create your views here.
def add(request):
    if request.method == 'POST':
        brand = request.POST['brand']
        year = request.POST['year']
        models.Car.objects.create(brand=brand, year=year)
        return redirect(reverse('cars:list'))
    else:
        return render(request, 'cars/add.html')

def delete(request):
    if request.method == 'POST':
        pk = request.POST['pk']
        try:
            models.Car.objects.get(pk=pk).delete()
        except:
            print('pk not found!')
        finally:
            return redirect(reverse('cars:list'))
    else:
        return render(request, 'cars/delete.html')

def list(request):
    all_cars = models.Car.objects.all()
    context = {'all_cars': all_cars}

    return render(request, 'cars/list.html', context=context)

car_site/cars/templates/cars/add.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1>ADD.HTML</h1>
        <h2>Add a new car to the database:</h2>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="brand">Brand:</label>
                <input class="form-control" type="text" id="brand" name="brand">
            </div>
            <div class="form-group">
                <label for="year">Year:</label>
                <input class="form-control" type="text" id="year" name="year">
            </div>
            <br>
            <input class="btn btn-primary" type="submit">
        </form>
    </div>
{% endblock %}

car_site/cars/templates/cars/delete.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1>DELETE.HTML</h1>
        <h2>Enter pk to delete car!</h2>
        <form action="" method="POST">
            {% csrf_token %}
                <div class="form-group">
                    <label for="pk">PK Number:</label>
                    <input class="form-control" type="text" id="pk" name="pk">
                </div>
                <br>
                <input class="btn btn-primary" type="submit">
        </form>
    </div>
{% endblock %}

car_site/cars/templates/cars/list.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1>LIST.HTML</h1>
            <ul>
                {% for car in all_cars %}
                    <li>{{ car }}</li>
                {% endfor %}
            </ul>
    </div>
{% endblock %}

car_site/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Title</title>
</head>
<body>
    {# NAVBAR #}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'cars:list' %}">LIST</a>
            <a class="nav-link" href="{% url 'cars:add' %}">ADD</a>
            <a class="nav-link" href="{% url 'cars:delete' %}">DELETE</a>
          </div>
        </div>
      </div>
    </nav>
    {% block content %}

    {% endblock %}
</body>
</html>