template_exercise/my_app/urls.py
from django.urls import path
from . import views

# register the app namespace
# URL NAMES
app_name = 'my_app'

urlpatterns = [
    path('', views.example_view, name='example'),
    path('variable/', views.variable_view, name='variable'),
]

template_exercise/template_exercise/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),
]

handler404 = 'template_exercise.views.my_custom_page_not_found_view'

template_exercise/my_app/views.py
from django.shortcuts import render

# Create your views here.
def example_view(request):
    # my app/templates/my_app/example.html
    return render(request, 'my_app/example.html')

def variable_view(request):
    my_var = {
        'first_name':'Seokkyu',
        'last_name':'Lee',
        'some_list': [
            1, 2, 3,
        ],
        'some_dict': {
            'inside_key': 'inside_value',
        },
        'user_logged_in': True,
    }
    return render(request, 'my_app/variable.html', context=my_var)

template_exercise/template_exercise/views.py
from django.shortcuts import render

def my_custom_page_not_found_view(request, exception):
    return render(request, "error_view.html", status=404)

template_exercise/my_app/templates/my_app/example.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <h1>EXAMPLE HTML TEMPLATE CONNECTED!</h1>
    <h1><a href="{% url 'my_app:variable' %}">VARIABLE</a></h1>
    <img src="{% static 'my_app/django.jpg' %}" alt="my image">

{% endblock content %}

template_exercise/my_app/templates/my_app/variable.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
    <h1>VARIABLE.HTML</h1>
    <h2>Hi {{ first_name | upper }} {{ last_name | capfirst }}</h2>
    {# <h2>in list { some_list }} index 0 is {{ some_list.0 }}</h2> #}
    <ul>
    {% for item in some_list %}
        <li>{{ item }}</li>
    {% endfor %}
    </ul>
    {% for k, v in some_dict.items %}
        <p> {{ k }} : {{ v }} </p>
    {% endfor %}

    {% if user_logged_in %}
        <p>USER {{ first_name }} LOGGED IN</p>
    {% else %}
        <p>USER LOGGED OUT</p>
    {% endif %}
    {# <h2>{{ some_dict }} {{ some_dict.inside_key }}</h2> #}
    {# THIS IS A DJANGO TEMPLATE COMMENT #}
    <!-- THIS IS HTML COMMENT -->
</body>
</html>

template_exercise/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BASE</title>
</head>
<body>
    <h1>THIS IS ABOVE THE BLOCK IN BASE.HTML</h1>
    {% block content %}

    {% endblock content%}
    <h1>THIS IS BELOW THE BLOCK IN BASE.HTML</h1>
</body>
</html>

template_exercise/templates/error_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>MY CUSTOM 404 PAGE</h1>
</body>
</html>